version: "2017-09-20"
pipeline:
- id: build
  type: script
  commands:
  - desc: Build and push docker image
    cmd: |
      IS_PR_BUILD=${CDP_PULL_REQUEST_NUMBER+"true"}
      if [[ ${IS_PR_BUILD} != "true" ]]
      then
          image=registry-write.opensource.zalan.do/teapot/aws-credentials-service:${CDP_BUILD_VERSION}
      else
          # PR build, use -test suffix
          image=registry-write.opensource.zalan.do/teapot/aws-credentials-service-test:${CDP_BUILD_VERSION}
      fi
      docker build -t $image .
      docker push $image
